name: vcf-demo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pandas=2.0.3
  - numpy=1.24.3
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - plotly=5.15.0
  - jupyter=1.0.0
  - notebook=7.0.2
  - pysam=0.21.0
  - cyvcf2=0.30.22
  - pybedtools=0.9.0
  - scipy=1.11.1
  - scikit-learn=1.3.0
  - pytest=7.4.0
  - pytest-cov=4.1.0
  - black=23.7.0
  - flake8=6.0.0
  - mypy=1.5.1
  - click=8.1.6
  - tqdm=4.65.0
  - colorama=0.4.6
  - jinja2=3.1.2
  - pip
  - pip:
    - nbconvert==7.7.3
